import './global.css';

import { cn } from '@nxnext/utils';
import { Inter as FontSans } from 'next/font/google';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={cn('min-h-screen bg-background font-sans antialiased dark', fontSans.variable)}
      >
        {children}
      </body>
    </html>
  );
}
